apiVersion: v1
kind: Namespace
metadata:
  name: $Namespace
  labels:
    name: $Namespace
---
apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  name: $NAME
  namespace: $Namespace 
  labels:
    application: $labels
spec:
  replicas: $replicas
  selector:
    matchLabels:
      application: $labels
  template:
    metadata:
      labels:
        application: $labels
    spec:
      containers:
        - name: $Container_name
          image: $Image_name
          ports:
            - containerPort: $port
          imagePullPolicy: Always
